lsi: false
safe: true
source: https://github.com/mad-lab-fau/carwatch
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: [CARwatch]
description: [A framework for tracking saliva samples in cortisol awakening response (CAR) studies.]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
  
